### ISSUE TITLE
Printing to console occurring in `DataBlockFinder` class

### ISSUE THREAD

**Issue by alex-gaudreault** [hpuhr/jASTERIX#38]
Hi,

While using the library, I've noticed that there is text being output to the console on every single call to `jASTERIX::jASTERIX::decodeData(...)`. I'm wondering if it would be possible to disable this printing via the debug flags in the constructor of `jASTERIX::jASTERIX` (this may have already been intended)? 

Thank you,
Alex

---
**Exact location of the print statement:**
[https://github.com/hpuhr/jASTERIX/blob/master/src/asterix/datablockfindertask.h](url) - Lines 49-54 (below)
```cpp
done_ = std::get<3>(ret);

loginf << "DataBlockFinderTask: ex pb " << parsed_bytes << " num db "
           << num_data_blocks << " done " << done_ << logendl;

jasterix_.addDataBlockChunk(std::move(jdata), error_, done_);
```

**Comment by hpuhr** [comment]
Hi,
  thank you for the issue report. You're correct, this is not intended, and fixed in the devel branch. Please use the devel branch source code for now, I'll do a version release soon to fix this also in the master.
